import type { AppProps } from "next/app";
import Head from "next/head";
import { ThemeProvider } from "styled-components";
import { ITheme } from "interfaces";
import { GlobalStyle } from "styles";

const theme: ITheme = {
  colors: {
    base: "#000000",
    primary: "#018762",
    secondary: "#1F1F1F",
    light: "#B0E0D3",
    lighter: "#EEEEEE",
    white: "#FFFFFF",
    gray: "rgb(81, 81, 81)",
  },
  font: {
    small: "0.85rem",
    default: "1rem",
    large: "1.5rem",
    big: "2rem",
    bigger: "3rem",
    family: "'Nunito', 'sans-serif'",
  },
  spacing: {
    small: "0.5rem",
    default: "1rem",
    big: "2rem",
    bigger: "3rem",
  },
};

/**
 * Home: The Landing page of the web app
 * @return {JSX.Element} The JSX Code for the Home Page
 */
export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>🌈 Desafio</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <ThemeProvider theme={theme}>
        <GlobalStyle />
        <Component {...pageProps} />
      </ThemeProvider>
    </>
  );
}
